name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip uv
        pip install pre-commit

    - name: Run pre-commit checks
      run: pre-commit run --all-files

  fork:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip uv
        pip install pre-commit

    - name: Setup git
      run: |
        git config --global user.email "test@example.com"
        git config --global user.name "Test User"

    - name: Test fork.sh script
      run: |
        # Test basic usage (script will do its own validation)
        ./fork.sh test-agent
        ./fork.sh test-agent-named TestAgent
